In [1]:
import pandas as pd
import numpy as np

In [2]:
def Fix_northern(data):
    tinh_thieu_CO = np.array(['Cao Bằng','Phú Thọ'])
    tinh_thieu_O3 = np.array(['Thái Nguyên'])
    tinh_thieu_NO2 = np.array(['Quảng Ninh'])
    col_CO = ['CO','NO2','O3','PM-10','PM-2-5','SO2']
    col_O3 = ['O3','PM-10','PM-2-5','SO2']
    col_NO2 = ['NO2','O3','PM-10','PM-2-5','SO2']
    
    fix = data.loc[data['Tỉnh'].isin(tinh_thieu_CO),col_CO]
    done = fix[col_CO].shift(1,axis="columns")
    data.loc[data['Tỉnh'].isin(tinh_thieu_CO),col_CO] = done.values
    
    fix = data.loc[data['Tỉnh'].isin(tinh_thieu_O3),col_O3]
    done = fix[col_O3].shift(1,axis="columns")
    data.loc[data['Tỉnh'].isin(tinh_thieu_O3),col_O3] = done.values
    
    fix = data.loc[data['Tỉnh'].isin(tinh_thieu_NO2),col_NO2]
    done = fix[col_NO2].shift(1,axis="columns")
    data.loc[data['Tỉnh'].isin(tinh_thieu_NO2),col_NO2] = done.values
    
    
    return data

In [3]:
data_37 = pd.read_csv("./Crawl Data/aqi_MienBac.txt",sep = '\t')

In [4]:
data_37

,Tỉnh,Vị trí,Nhiệt độ,Độ ẩm,Tốc độ gió,Áp suất,Ngày giờ,VN_AQI,CO,NO2,O3,PM-10,PM-2-5,SO2
0,Gia Lai,"('13.998599', '107.996482')",28.77,57,2.72,1010,03/07/2021 08:00,50,4,10,5,36,50.0,14.0
1,Ðà Nẵng,"('16.074', '108.217')",35.00,49,0.51,1007,03/07/2021 08:00,43,10,10,13,34,43.0,40.0
2,Cao Bằng,"('22.6782', '106.245')",29.54,80,0.63,1004,03/07/2021 08:00,74,0,1,57,74,1.0,NaN
3,Phú Thọ,"('21.33847', '105.3673')",31.92,65,1.54,1003,03/07/2021 08:00,30,9,10,17,30,NaN,NaN
4,Thái Nguyên,"('21.593151', '105.8431043')",31.88,67,0.77,1003,03/07/2021 08:00,45,6,15,43,45,15.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470,Phú Thọ,"('21.33847', '105.3673')",32.92,63,2.91,1004,06/07/2021 19:00,28,6,28,6,11,NaN,NaN
471,Thái Nguyên,"('21.593151', '105.8431043')",32.88,71,3.09,1004,06/07/2021 19:00,68,6,9,55,68,8.0,NaN
472,Hà Nội,"('21.0491', '105.8831')",33.01,66,4.88,1004,06/07/2021 19:00,11,11,11,9,9,7.0,8.0
473,Bắc Ninh,"('21.1527453', '106.111371')",33.06,68,5.32,1004,06/07/2021 19:00,39,1,6,12,36,39.0,35.0
474,Quảng Ninh,"('21.006517', '107.344252')",33.06,68,5.32,1004,06/07/2021 18:00,66,9,20,1,3,66.0,NaN

In [5]:
data_37 = Fix_northern(data_37)
tinh_thieu_CO = np.array(['Cao Bằng','Phú Thọ','Quảng Ninh'])
tinh_thieu_O3 = np.array(['Thái nguyên'])
tinh_thieu_NO2 = np.array(['Quảng Ninh'])
data_37[data_37['Tỉnh'].isin(tinh_thieu_CO)]

,Tỉnh,Vị trí,Nhiệt độ,Độ ẩm,Tốc độ gió,Áp suất,Ngày giờ,VN_AQI,CO,NO2,O3,PM-10,PM-2-5,SO2
2,Cao Bằng,"('22.6782', '106.245')",29.54,80,0.63,1004,03/07/2021 08:00,74,NaN,0.0,1.0,57.0,74.0,1.0
3,Phú Thọ,"('21.33847', '105.3673')",31.92,65,1.54,1003,03/07/2021 08:00,30,NaN,9.0,10.0,17.0,30.0,NaN
8,Quảng Ninh,"('21.006517', '107.344252')",32.06,50,1.83,1003,03/07/2021 07:00,59,9.0,NaN,20.0,1.0,3.0,59.0
11,Cao Bằng,"('22.6782', '106.245')",29.77,79,0.75,1004,03/07/2021 09:00,76,NaN,0.0,1.0,64.0,76.0,1.0
12,Phú Thọ,"('21.33847', '105.3673')",32.92,59,1.81,1003,03/07/2021 09:00,29,NaN,7.0,16.0,16.0,29.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,Phú Thọ,"('21.33847', '105.3673')",34.92,54,1.76,1000,06/07/2021 16:00,30,NaN,7.0,30.0,6.0,11.0,NaN
466,Quảng Ninh,"('21.006517', '107.344252')",35.06,49,6.44,1001,06/07/2021 15:00,65,8.0,NaN,20.0,2.0,7.0,65.0
469,Cao Bằng,"('22.6782', '106.245')",28.33,76,1.00,1005,06/07/2021 19:00,123,NaN,0.0,1.0,122.0,123.0,1.0
470,Phú Thọ,"('21.33847', '105.3673')",32.92,63,2.91,1004,06/07/2021 19:00,28,NaN,6.0,28.0,6.0,11.0,NaN
474,Quảng Ninh,"('21.006517', '107.344252')",33.06,68,5.32,1004,06/07/2021 18:00,66,9.0,NaN,20.0,1.0,3.0,66.0

In [6]:
data_nort_add = pd.read_csv("./Crawl Data/Fixed data/aqi_MienBac.txt",sep = '\t')
data_nort_add = Fix_northern(data_nort_add)

In [7]:
total = pd.concat([data_37,data_nort_add], ignore_index = True )

In [8]:
import os             
all_files = os.listdir("./Crawl Data/Addition/")
all_files

['Bac Ninh.txt',
 'Can tho.txt',
 'Cao bang.txt',
 'Da nang.txt',
 'Gia lai.txt',
 'Ha noi.txt',
 'HCM.txt',
 'Hung Yen.txt',
 'Nghe An.txt',
 'Phu tho.txt',
 'Quang Ninh.txt',
 'Thai nguyen.txt']

In [9]:
all_files = ['Bac Ninh.txt','Cao bang.txt','Da nang.txt','Gia lai.txt','Ha noi.txt','Hung Yen.txt','Phu tho.txt','Quang Ninh.txt','Thai nguyen.txt']
for file in all_files:
    path = './Crawl Data/Addition/'
    data_add = pd.read_csv(path + file,sep = '\t')
    data_add = Fix_northern(data_add)
    total = pd.concat([total,data_add],ignore_index = True )

In [10]:
data_trung = pd.read_csv("./Crawl Data/aqi_MienTrung.txt",sep = '\t')
data_add = pd.read_csv("./Crawl Data/Fixed data/aqi_MienTrung.txt",sep = '\t')
total_trung = pd.concat([data_trung,data_add],ignore_index = True)
all_files = ['Nghe An.txt']
for file in all_files:
    path = './Crawl Data/Addition/'
    data_add = pd.read_csv(path + file,sep = '\t')
    total_trung = pd.concat([total_trung,data_add],ignore_index = True )
total_trung.head()

,Tỉnh,Vị trí,Nhiệt độ,Độ ẩm,Tốc độ gió,Áp suất,Ngày giờ,VN_AQI,PM-10,PM-2-5
0,Nghệ An,"('18.675369', '105.690945')",31.60,61,3.18,1004,03/07/2021 08:00,26,26,19
1,Nghệ An,"('18.675369', '105.690945')",33.68,54,4.05,1004,03/07/2021 09:00,23,23,15
2,Nghệ An,"('18.675369', '105.690945')",35.45,47,4.25,1003,03/07/2021 10:00,20,20,11
3,Nghệ An,"('18.675369', '105.690945')",36.47,44,4.75,1002,03/07/2021 11:00,19,19,8
4,Nghệ An,"('18.675369', '105.690945')",36.82,47,4.80,1004,03/07/2021 12:00,17,17,6

In [11]:
data_nam = pd.read_csv("./Crawl Data/aqi_MienNam.txt",sep = '\t')
data_add = pd.read_csv("./Crawl Data/Fixed data/aqi_MienNam.txt",sep = '\t')
total_nam = pd.concat([data_nam,data_add],ignore_index = True)
all_files = ['Can tho.txt','HCM.txt']
for file in all_files:
    path = './Crawl Data/Addition/'
    data_add = pd.read_csv(path + file,sep = '\t')
    total_nam = pd.concat([total_nam,data_add],ignore_index = True )
total_nam

,Tỉnh,Vị trí,Nhiệt độ,Độ ẩm,Tốc độ gió,Áp suất,Ngày giờ,VN_AQI,PM-10,PM-2-5
0,Tp. Hồ Chí Minh,"('10.65961', '106.727916')",31.01,79,1.54,1009,03/07/2021 08:00,23,23,21
1,Cần Thơ,"('10.026977', '105.768249')",29.99,79,1.54,1009,03/07/2021 08:00,21,21,19
2,Tp. Hồ Chí Minh,"('10.65961', '106.727916')",32.01,70,1.54,1009,03/07/2021 09:00,24,24,23
3,Cần Thơ,"('10.026977', '105.768249')",30.99,79,2.06,1009,03/07/2021 09:00,19,19,16
4,Tp. Hồ Chí Minh,"('10.65961', '106.727916')",34.01,62,2.57,1008,03/07/2021 10:00,26,26,25
...,...,...,...,...,...,...,...,...,...,...
163,Tp. Hồ Chí Minh,"('10.65961', '106.727916')",26.01,100,1.66,1004,06/07/2021 05:00,53,53,36
164,Tp. Hồ Chí Minh,"('10.65961', '106.727916')",26.01,100,0.51,1004,06/07/2021 04:00,42,42,25
165,Tp. Hồ Chí Minh,"('10.65961', '106.727916')",25.01,100,1.12,1004,06/07/2021 03:00,46,46,29
166,Tp. Hồ Chí Minh,"('10.65961', '106.727916')",27.01,89,1.54,1006,06/07/2021 18:00,11,11,7
167,Tp. Hồ Chí Minh,"('10.65961', '106.727916')",27.01,85,3.56,1004,06/07/2021 17:00,10,10,6

In [12]:
final = pd.concat([total,total_nam,total_trung],ignore_index = True)

In [13]:
total['Tỉnh'].unique()

array(['Gia Lai', 'Ðà Nẵng', 'Cao Bằng', 'Phú Thọ', 'Thái Nguyên',
       'Hà Nội', 'Bắc Ninh', 'Hưng Yên', 'Quảng Ninh'], dtype=object)

In [14]:
def Mien(row):
    bac = np.array(['Cao Bằng', 'Phú Thọ', 'Thái Nguyên',
       'Hà Nội', 'Bắc Ninh', 'Hưng Yên', 'Quảng Ninh'])
    trung = np.array(['Gia Lai', 'Ðà Nẵng','Nghệ An'])
    nam = np.array(['Tp. Hồ Chí Minh','Cần Thơ'])
    if  row['Tỉnh'] in bac:
        return 1
    if row['Tỉnh'] in trung:
        return 2
    if row['Tỉnh'] in nam:
        return 3
final['Miền'] = final.apply (lambda row: Mien(row), axis=1)

In [15]:
final.sort_values(by=['Tỉnh','Ngày giờ'])

,Tỉnh,Vị trí,Nhiệt độ,Độ ẩm,Tốc độ gió,Áp suất,Ngày giờ,VN_AQI,CO,NO2,O3,PM-10,PM-2-5,SO2,Miền
6,Bắc Ninh,"('21.1527453', '106.111371')",32.06,50,1.83,1003,03/07/2021 08:00,107,3.0,17.0,10.0,70.0,107.0,34.0,1
15,Bắc Ninh,"('21.1527453', '106.111371')",33.06,44,3.05,1002,03/07/2021 09:00,91,3.0,16.0,13.0,73.0,91.0,38.0,1
24,Bắc Ninh,"('21.1527453', '106.111371')",34.06,41,3.94,1002,03/07/2021 10:00,74,2.0,8.0,13.0,74.0,69.0,39.0,1
33,Bắc Ninh,"('21.1527453', '106.111371')",34.06,40,4.61,1001,03/07/2021 11:00,76,1.0,7.0,13.0,76.0,62.0,36.0,1
42,Bắc Ninh,"('21.1527453', '106.111371')",34.06,40,4.61,1001,03/07/2021 12:00,81,1.0,5.0,17.0,81.0,67.0,34.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
451,Ðà Nẵng,"('16.074', '108.217')",30.00,70,0.51,1001,06/07/2021 15:00,30,8.0,11.0,12.0,20.0,30.0,27.0,2
460,Ðà Nẵng,"('16.074', '108.217')",29.00,74,1.54,1001,06/07/2021 16:00,31,7.0,11.0,14.0,22.0,31.0,28.0,2
663,Ðà Nẵng,"('16.074', '108.217')",28.00,79,1.18,1004,06/07/2021 17:00,30,9.0,11.0,14.0,21.0,30.0,26.0,2
662,Ðà Nẵng,"('16.074', '108.217')",29.00,74,0.52,1003,06/07/2021 18:00,28,10.0,11.0,13.0,19.0,28.0,27.0,2
468,Ðà Nẵng,"('16.074', '108.217')",28.00,83,0.51,1004,06/07/2021 19:00,32,13.0,11.0,9.0,23.0,32.0,27.0,2

In [16]:
final.drop(final.loc[final['Tỉnh']== 'Hưng Yên'].index, inplace=True)

In [17]:
final.to_csv('aqi_VietNam.csv', sep='\t', encoding='utf-8',index = False)

In [18]:
for tinh in final['Tỉnh'].unique().tolist():
    print(tinh+ ':' + str(final[final['Tỉnh'] == tinh].shape))

Gia Lai:(84, 15)
Ðà Nẵng:(84, 15)
Cao Bằng:(84, 15)
Phú Thọ:(84, 15)
Thái Nguyên:(84, 15)
Hà Nội:(84, 15)
Bắc Ninh:(84, 15)
Quảng Ninh:(84, 15)
Tp. Hồ Chí Minh:(84, 15)
Cần Thơ:(84, 15)
Nghệ An:(84, 15)